# Numpy
+ Supports multi-dimensional arrays
+ Installation: `pip install numpy`
+ Usage: `import numpy as np`

In [1]:
import numpy as np
from copy import deepcopy

# Multi-dimensional Arrays

In [2]:
my_array = [0, 1]
print(my_array[0], my_array)

my_array = [[0, 1], [2, 3]]
print(my_array[0][1], my_array)

my_array = [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
print(my_array[1][0][1], my_array)

0 [0, 1]
1 [[0, 1], [2, 3]]
5 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [3]:
my_array = np.array([0, 1])
print(my_array.dtype, my_array.shape, my_array[0])
print(my_array); print()

my_array = np.array([[0, 1], [2, 3]])
print(my_array.dtype, my_array.shape, my_array[0, 1])
print(my_array); print()

my_array = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print(my_array.dtype, my_array.shape, my_array[1, 0, 1])
print(my_array); print()

int64 (2,) 0
[0 1]

int64 (2, 2) 1
[[0 1]
 [2 3]]

int64 (2, 2, 2) 5
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



# Reshaping & Type Conversion

In [4]:
my_array = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print('Before Conversion:', my_array.dtype)

my_array = my_array.astype(float)
print('After Conversion', my_array.dtype)

print('Before Reshaping:', my_array.shape)
my_array = my_array.reshape(8) # or .reshape(-1)
print('After Reshaping:', my_array.shape)
print('Final Array:', my_array)

Before Conversion: int64
After Conversion float64
Before Reshaping: (2, 2, 2)
After Reshaping: (8,)
Final Array: [0. 1. 2. 3. 4. 5. 6. 7.]


# Indexing

In [5]:
my_array = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print(my_array[0])
print()

print(my_array[0, 0])
print()

print(my_array[0, 0, 0])
print()

print(my_array[:, 0])
print()

print(my_array[:, :, 0])
print()

print(my_array < 5)
print()

print(my_array[my_array < 5])
print()

print(my_array[[0, 0]])

[[0 1]
 [2 3]]

[0 1]

0

[[0 1]
 [4 5]]

[[0 2]
 [4 6]]

[[[ True  True]
  [ True  True]]

 [[ True False]
  [False False]]]

[0 1 2 3 4]

[[[0 1]
  [2 3]]

 [[0 1]
  [2 3]]]


# Unary Operations

In [6]:
my_array = np.array([[0, 1], [2, 3]])
print(-my_array)
print()

print(np.sin(my_array))
print()

print(my_array)

[[ 0 -1]
 [-2 -3]]

[[0.         0.84147098]
 [0.90929743 0.14112001]]

[[0 1]
 [2 3]]


# Binary Operations

In [7]:
my_array = np.array([[0, 1], [2, 3]])

print(my_array * 2)
print()

print(my_array + 2)
print()

print(my_array + my_array)
print()

print(my_array + [[1, 0], [1, 0]])

[[0 2]
 [4 6]]

[[2 3]
 [4 5]]

[[0 2]
 [4 6]]

[[1 1]
 [3 3]]


# Reduction Operations

In [8]:
my_array = np.array([[0, 1], [2, 3]])

print(my_array.sum())
print()

print(my_array.sum(axis=0))
print()

print(my_array.sum(axis=1))
print()

6

[2 4]

[1 5]



# View vs Copy

In [9]:
my_array = np.array([[0, 1], [2, 3]])
view_array = my_array[0]
view_array[0] = 10

print(view_array)
print(my_array)
print()

my_array = np.array([[0, 1], [2, 3]])
copy_array = deepcopy(my_array[0])
copy_array[0] = 10

print(view_array)
print(my_array)
print()

my_array = 0
print(my_array)

my_array = np.array([[0, 1], [2, 3]])
my_array[:] = 0
print(my_array)

[10  1]
[[10  1]
 [ 2  3]]

[10  1]
[[0 1]
 [2 3]]

0
[[0 0]
 [0 0]]
